---

- name: Check destination location
  stat:
    path: "{{ item.destination }}"
  register: scriptsDestinationStatus
  with_items:
    - "{{ scripts }}"

- name: Create destination location
  file:
    path: "{{ item.item.destination }}"
    state: directory
  with_items:
    - "{{ scriptsDestinationStatus.results }}"
  when:
    - not item.stat.exists

- name: Copy script to location with permissions
  template:
    src: "{{ item.item.source }}{{ item.item.name }}.{{ item.item.ext }}.j2"
    dest: "{{ item.item.destination }}/{{ item.item.name }}.{{ item.item.ext }}"
    mode: "{{ item.item.mode | default('0644') }}"
    owner: "{{ item.item.owner | default('root') }}"
    group: "{{ item.item.group | default('root') }}"
  with_items:
    - "{{ scriptsDestinationStatus.results }}"
